title: Block Transfer
email: devs@blocktransfer.io
description: >-
  Stellar interface for Block Transfer,
  a blockchain transfer agent for global financial markets.
baseurl: ""
url: "stellar.blocktransfer.io"
twitter_username: blocktransfer
github_username:  blocktransfer

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
